# permissions for end users to view supplies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supply-viewer-role
rules:
- apiGroups:
  - fund.demo.com
  resources:
  - supplies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fund.demo.com
  resources:
  - supplies/status
  verbs:
  - get
